Neos:
  Form:
    yamlPersistenceManager:
      savePath: 'resource://WL.WeinLaden/Private/Form/'

    presets:
      default:
        formElementTypes:
          'Neos.Form:SingleLineText':
            properties:
              elementClassAttribute: 'form-control'
          'Neos.Form:MultiLineText':
            properties:
              elementClassAttribute: 'form-control'
          'Neos.Form:SingleSelectDropdown':
            properties:
              elementClassAttribute: 'form-control'

  ContentRepository:
    contentDimensions:
      language:
        label: Language
        icon: icon-language
        default: de
        defaultPreset: de
        presets:
          de:
            label: Deutsch
            values:
              - de
            uriSegment: deutsch
          en:
            label: English
            values:
              - en
            uriSegment: english
          fr:
            label: Français
            values:
              - fr
              - en
            uriSegment: francais
