TYPO3:
  Form:
    yamlPersistenceManager:
      savePath: 'resource://WL.WeinLaden/Private/Form/'

    presets:
      default:
        formElementTypes:
          'TYPO3.Form:SingleLineText':
            properties:
              elementClassAttribute: 'form-control'
          'TYPO3.Form:MultiLineText':
            properties:
              elementClassAttribute: 'form-control'
          'TYPO3.Form:SingleSelectDropdown':
            properties:
              elementClassAttribute: 'form-control'